name: Build and testing.

# Run lerna:build and lerna:test on pull request creation against master
on:
  pull_request:
    branches: [master]

env:
  NODE_VERSION: 18.x

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run lerna:build
      - run: npm run lerna:test
